"""initial pharmacy migration

Revision ID: 646520d3297e
Revises: 
Create Date: 2026-08-19 22:47:56.513863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646520d3297e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.String(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'DEPLETED', name='batchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_batches_expiry_date'), 'medication_batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_medication_batches_id'), 'medication_batches', ['id'], unique=False)
    op.create_index(op.f('ix_medication_batches_medication_name'), 'medication_batches', ['medication_name'], unique=False)
    op.create_table('dispense_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.String(), nullable=False),
    sa.Column('quantity_dispensed', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('dispensed_at', sa.DateTime(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['medication_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispense_logs_id'), 'dispense_logs', ['id'], unique=False)
    op.create_index(op.f('ix_dispense_logs_patient_id'), 'dispense_logs', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispense_logs_patient_id'), table_name='dispense_logs')
    op.drop_index(op.f('ix_dispense_logs_id'), table_name='dispense_logs')
    op.drop_table('dispense_logs')
    op.drop_index(op.f('ix_medication_batches_medication_name'), table_name='medication_batches')
    op.drop_index(op.f('ix_medication_batches_id'), table_name='medication_batches')
    op.drop_index(op.f('ix_medication_batches_expiry_date'), table_name='medication_batches')
    op.drop_table('medication_batches')
    # ### end Alembic commands ###
